chat/api/urls.py
from django.conf.urls import url
from .views import (
    ConversationListAPIView, MessageListAPIView, SongListAPIView, UserListAPIView,
    ConversationDetailAPIView, MessageDetailAPIView, SongDetailAPIView,
    ConversationDeleteAPIView, MessageDeleteAPIView, MessageCreateAPIView,
    UserCreateAPIView, UserLoginAPIView, ConversationCreateAPIView
)

app_name = 'chat'

urlpatterns = [
    url(r'^conversation/$', ConversationListAPIView.as_view(), name='conversation_list'),
    url(r'^conversation/(?P<pk>[0-9]+)/$', ConversationDetailAPIView.as_view(), name='conversation_detail'),
    url(r'^conversation/(?P<conversation_id>[0-9]+)/messages/$', MessageListAPIView.as_view(),
        name='message_list'),
    url(r'^conversation/(?P<conversation_id>[0-9]+)/messages/(?P<pk>[0-9]+)/$', MessageDetailAPIView.as_view(),
        name='message_detail'),

    url(r'^conversation/(?P<conversation_id>[0-9]+)/messages/create/$', MessageCreateAPIView.as_view(),
        name='message_create'),

    url(r'^conversation/create/$', ConversationCreateAPIView.as_view(),
        name='conversation_create'),
    url(r'^conversation/(?P<pk>[0-9]+)/delete/$', ConversationDeleteAPIView.as_view(),
        name='conversation_delete'),
    url(r'^conversation/(?P<conversation_id>[0-9]+)/messages/(?P<pk>[0-9]+)/delete/$', MessageDeleteAPIView.as_view(),
        name='message_delete'),



    url(r'^songs(?P<q>.+)$', SongListAPIView.as_view(), name='song_list'),
    url(r'^login/$', UserLoginAPIView.as_view(), name='login'),
    url(r'^register/$', UserCreateAPIView.as_view(), name='register'),
    url(r'^users/$', UserListAPIView.as_view(), name='user_list'),
    url(r'^songs/(?P<pk>[0-9]+)/$', SongDetailAPIView.as_view(), name='song_detail'),
]

chat/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'chat'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<user_id>[0-9]+)/$', views.fetch_conversation, name='conversation'),
    url(r'^search/$', views.search_song, name='search_song'),
    # url(r'^add_user/$', views.index, name='add_user'),

    url(r'^api/', include('chat.api.urls', namespace='chat-api')),
]

songapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from chat import views as core_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^chat/', include('chat.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include('haystack.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
import json
from django.db import models
from django.contrib.auth.models import User
from channels import Group
from django_languages.fields import LanguageField
from django_countries.fields import CountryField


class Artist(models.Model):
    SEX = (  # correct field
        ('M', 'Male'),
        ('F', 'Female'),
        ('U', 'Unknown')
    )
    artist_name = models.CharField(max_length=250)  # correct field
    artist_gender = models.CharField(max_length=1, choices=SEX, null=True, blank=True)  # correct field
    artist_impression = models.IntegerField(default=0)  # correct field  # How many times it's been used

    def __str__(self):
        return self.artist_name


class Album(models.Model):  # correct field # the equivalent of movie for a dialogue
    album_name = models.CharField(max_length=250)
    album_release_date = models.DateField(null=True, blank=True)
    album_impression = models.IntegerField(default=0)  # How many times it's been used

    def __str__(self):
        return self.album_name


class Alias(models.Model):
    alias_name = models.CharField(max_length=250, null=True, blank=True)
    alias_impression = models.IntegerField(default=0)

    def __str__(self):
        return self.alias_name


class Genre(models.Model):
    genre_name = models.CharField(max_length=50, null=True, blank=True)
    genre_impression = models.IntegerField(default=0)  # How many times it's been used

    def __str__(self):
        return self.genre_name


class Mood(models.Model):
    MOOD = (  # correct field
        ('ANGR', 'Anger'),
        ('DSGT', 'Disgust'),
        ('FEAR', 'Fear'),
        ('HAPP', 'Happy'),
        ('SADN', 'Sadness'),
        ('SURP', 'Surprise')
    )
    mood_name = models.CharField(max_length=4, choices=MOOD, null=True, blank=True)
    mood_impression = models.IntegerField(default=0)  # How many times it's been used

    def __str__(self):
        return self.mood_name


class Conversation(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user2')
    started_at = models.DateTimeField('date started', auto_now=True)

    class Meta:
        unique_together = (("user1", "user2"), ("user2", "user1"),)

    def __str__(self):
        return str(self.id)

    @property
    # def websocket_group(self):
    #     return Group("conversation-%s" % self.id)
    def websocket_group(self):
        return Group("room")

    def send_message(self, message, user):
        conversation = Conversation.objects.get(pk=str(self.id))
        if  user == conversation.user1.username:
            recipient = conversation.user2.username
        else:
            recipient = conversation.user1.username
        final_msg = {'conversation': str(self.id), 'message': message, 'username': user, 'recipient': recipient}
        self.websocket_group.send(
            {"text": json.dumps(final_msg)}
        )


class Song(models.Model):
    CATEGORY = (  # correct field
        ('SG', 'Song'),
        ('SP', 'Speech')
    )
    category = models.CharField(max_length=2, choices=CATEGORY)  # for filtering search res
    song_name = models.CharField(max_length=200)
    song_desc = models.CharField(max_length=500)
    song = models.FileField(upload_to='songs/', default=None)  # the song itself in media format
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, null=True, blank=True)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True, blank=True)
    alias = models.ForeignKey(Alias, on_delete=models.CASCADE, null=True, blank=True)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, null=True, blank=True)
    mood = models.ForeignKey(Mood, on_delete=models.CASCADE, null=True, blank=True)
    song_language = LanguageField()  # to create a language field # for filtering search res
    song_country = CountryField()  # to create a language field
    created_at = models.DateTimeField('date created', auto_now=True)
    last_used = models.DateTimeField('date last used', null=True, blank=True)
    song_impression = models.IntegerField(default=0)

    def __unicode__(self):
        return self.song_desc


class Message(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    created_at = models.DateTimeField('date created', auto_now=True)
    message = models.CharField(max_length=1000)

    def __str__(self):
        return self.message

chat/forms.py
from django import forms
from django.contrib.auth.models import User


class NetworkForm(forms.Form):

    def __init__(self, uid_list, *args, **kwargs):
        super(NetworkForm, self).__init__(*args, **kwargs)
        self.fields['user_id'].queryset = User.objects.filter(id__in=uid_list)

    error_css_class = 'error'

    user_id = forms.ModelChoiceField(queryset=User.objects.all(), empty_label='None', label='',
                                     widget=forms.Select(attrs={'class': 'all_users'}),
                                     error_messages={"invalid_choice": "User has already added you. Check out your network below."},
                                     )

chat/api/views.py
from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView, DestroyAPIView
from haystack.query import SearchQuerySet
from rest_framework.permissions import (
    AllowAny, IsAdminUser, IsAuthenticated
)
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from django.db.models import Q
from django.contrib.auth.models import User
from chat.models import Conversation, Message, Song
from .serializers import (ConversationSerializer,
                          ConversationCreateSerializer,
                          MessageCreateSerializer,
                          MessageSerializer,
                          SongSerializer,
                          UserSerializer,
                          UserCreateSerializer,
                          UserLoginSerializer,
                          )
from rest_framework.validators import ValidationError


# creates restful API conversation list - users see only related conversation
class ConversationListAPIView(ListAPIView):
    serializer_class = ConversationSerializer
    permission_classes = [IsAuthenticated]

    # overwriting default queryset by method so that logged in use would only see his conversations
    def get_queryset(self):
        queryset = Conversation.objects.filter(Q(user1=self.request.user) |
                                               Q(user2=self.request.user)).order_by(
            '-started_at')
        return queryset


# creates restful API conversation detail for each ID - users can only query related conversation
class ConversationDetailAPIView(RetrieveAPIView):
    serializer_class = ConversationSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Conversation.objects.filter(Q(user1=self.request.user) |
                                               Q(user2=self.request.user)).order_by('-started_at')
        return queryset


class ConversationCreateAPIView(CreateAPIView):
    serializer_class = ConversationCreateSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Conversation.objects.filter(Q(user1=self.request.user) |
                                               Q(user2=self.request.user)).order_by('-created_at')
        return queryset

    def perform_create(self, serializer):
        other_user = User.objects.get(pk=self.request.data["user2"])
        if self.request.user == other_user:
            raise ValidationError("Both parties cannot be the same")
        else:
            try:
                Conversation.objects.get(
                    (Q(user1=self.request.user) & Q(user2=other_user)) |
                    (Q(user1=other_user) & Q(user2=self.request.user)))
                raise ValidationError("Conversation already exists")
            except Conversation.DoesNotExist:
                serializer.save(user1=self.request.user,
                                )
                return Response(serializer.data, status=HTTP_200_OK)


# creates restful API for deleting particular conversation using ID - users can only delete related conversation
class ConversationDeleteAPIView(DestroyAPIView):
    serializer_class = MessageSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Conversation.objects.filter(Q(user1=self.request.user) | Q(user2=self.request.user)).order_by(
            '-created_at')
        return queryset


# for creating messages constrained by the conversation a user is in, hence
# the receiver, conversation and sender is static, only messages can change
class MessageCreateAPIView(CreateAPIView):
    serializer_class = MessageCreateSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Message.objects.filter(Q(sender=self.request.user) |
                                          Q(receiver=self.request.user)).order_by('-created_at')

        queryset_next = queryset.filter(Q(conversation=self.request.parser_context['kwargs']['conversation_id']))
        return queryset_next

    def perform_create(self, serializer):
        conversation = Conversation.objects.get(pk=self.request.parser_context['kwargs']['conversation_id'])
        if self.request.user == conversation.user1:
            receiver = conversation.user2
        else:
            receiver = conversation.user1
        serializer.save(sender=self.request.user,
                        conversation=conversation,
                        receiver=receiver)


# creates restful API messages list - users see messages sent/ received to/ from them
# user can only see all messages underlying conversation he's put in the url for
# url access is /conversation/12/messages/
class MessageListAPIView(ListAPIView):
    serializer_class = MessageSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Message.objects.filter(Q(sender=self.request.user) |
                                          Q(receiver=self.request.user)).order_by('-created_at')

        queryset_next = queryset.filter(Q(conversation=self.request.parser_context['kwargs']['conversation_id']))
        return queryset_next


# creates restful API messages detail for each ID - users can only query related (sent/ receipt) messages
# user can only see selected message underlying particular conversation
# url access is /conversation/12/messages/232/
class MessageDetailAPIView(RetrieveAPIView):
    serializer_class = MessageSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Message.objects.filter(Q(sender=self.request.user) |
                                          Q(receiver=self.request.user)).order_by('-created_at')

        queryset_next = queryset.filter(Q(conversation=self.request.parser_context['kwargs']['conversation_id']))
        return queryset_next


# creates restful API for deleting particular message using ID - users can only delete related messages
# user can only go to a conversation, select message underlying conversation and then delete
class MessageDeleteAPIView(DestroyAPIView):
    serializer_class = MessageSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        queryset = Message.objects.filter(Q(sender=self.request.user) |
                                          Q(receiver=self.request.user)).order_by('-created_at')

        queryset_next = queryset.filter(Q(conversation=self.request.parser_context['kwargs']['conversation_id']))
        return queryset_next


class SongListAPIView(ListAPIView):
    serializer_class = SongSerializer
    permission_classes = [IsAdminUser]

    def get_queryset(self):
        text = self.request.query_params.get('q', None)
        if text is not None:
            songs = SearchQuerySet().autocomplete(text=text)
            if songs:
                pk_values = [song.object.pk for song in songs]
                query = reduce(lambda qu, pk_value: qu|Q(pk=pk_value), pk_values, Q())
                queryset = Song.objects.filter(query)
                return queryset
        elif text is None:
            queryset = Song.objects.all()
            return queryset


# creates restful API song list
class SongDetailAPIView(RetrieveAPIView):
    queryset = Song.objects.all()
    serializer_class = SongSerializer
    permission_classes = [IsAdminUser]


# creates restful API user list
class UserListAPIView(ListAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class UserCreateAPIView(CreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserCreateSerializer


class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)
        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>Chat</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Megrim|Lato|Pacifico" type="text/css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}"/>
</head>

<body>
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#" style="color: white;">SongApp</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'chat:index' %}" style="background-color: transparent !important; color: white;">Home</a></li>
                <li><a href="#" style="background-color: transparent !important; color: white;">{{ request.user }}</a></li>
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" style="background-color: transparent !important; color: white;">Log Out</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}" style="background-color: transparent !important; color: white;">Log In</a></li>
                {% endif %}
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'signup' %}" style="background-color: transparent !important; color: white;">Sign up</a></li>
                {% endif %}
            </ul>
       </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

chat/templates/chat/index.html
{% extends 'chat/base.html' %}
{% load static %}
{% block body %}
<link href="https://fonts.googleapis.com/css?family=Fredoka+One" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}"/>
<div class="container">
    <div class="row">
            <div class="col-md-7">
                <div class="row" style="font-family: 'Fredoka One', cursive; font-size: 90px;
                                    text-shadow: 5px 5px #8c4646; color: #f2e394;">
                    Welcome to SongApp.</div>
                <br>
                <br>
                <br>
                <div class="row" style="font-family: 'Fredoka One', cursive; font-size: 50px;
                                    text-shadow: 5px 5px #8c4646; color: #f2e394;">
                    Made with a heart </div>
                <div class="row" style="font-family: 'Fredoka One', cursive; font-size: 50px;
                                    text-shadow: 5px 5px #8c4646; color: #f2e394;">
                    and some lines of codes,</div>
                <div class="row" style="font-family: 'Fredoka One', cursive; font-size: 50px;
                                    text-shadow: 5px 5px #8c4646; color: #f2e394;">
                     just for you!</div>
            </div>

        <div class="col-md-3 col-md-offset-1">
            <div class="row"
                 style="text-shadow: 2px 2px 3px #8c4646; color: #f2e394;">
                <h2>Add User</h2>
            </div>
            <div class="row">
                <form action="{% url 'chat:index' %}" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-warning" value="{{ user_id }}" style="float: left;">Submit</button>
                </form>
            </div>
            <br>
            <div class="row" style="text-shadow: 2px 2px 3px #8c4646; color: #f2e394;">
                <h2>My Network</h2>
                <div style="text-shadow: 2px 2px 3px #8c4646; color: #cce5cc;">
                    <h5>Add users to your network from above</h5>
                </div>
            </div>
            {% for user in  user_list %}
                <div class="row" style="text-transform: capitalize;">
                    <h3><a href="{% url 'chat:conversation' user.id %}" style="color: #fff">{{ user.username }}</a></h3>
                </div>
            {% endfor %}
        </div>
    </div>
</div>


<script>
    {% for user in user_list %}
        $('#select_user').append("<option value={{user.username}}>{{user.username}}</option>");
    {% endfor %}
</script>

{% endblock %}

chat/templates/chat/messages.html
{% extends 'chat/base.html' %}
{% load static %}
{% block body %}

<script src="{% static 'js/ajax.js' %}"></script>
<link href="https://fonts.googleapis.com/css?family=Amatic+SC|Open+Sans|Alegreya+Sans+SC:b" type="text/css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'chat/audio_switch.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'chat/style.css' %}"/>



<div class="container" id="container">
    <div class="row">
        <div class="col-md-3" id="user_list">
                {% for user in  user_list %}
                    <div class="row  user_list_row">
                        <div class="col-md-3">
                            <img src="{% static 'img/cv-icon-3.png' %}"
                                 style="height: 57px; width: 51px; padding-top: 5px;">
                        </div>
                        <div class="col-md-6" style="cursor: pointer; padding-bottom: 8px;"
                             onclick="window.location='{% url 'chat:conversation' user.id %}';">
                            <strong><h3>{{ user.username }}</h3></strong>
                        </div>
                        <div class="col-md-3" id="notification_{{ user.username }}" style="padding-top: 17px"><div></div></div>
                    </div>
                {% endfor %}
        </div>
        <div class="col-md-9" id="chats">
            <div class="col-md-12">
                <div class="row" id="user_name">
                    <div class="col-md-10">{{ receiver }}</div>
                    <div class="col-md-2">
                        <label class="switch">
                            <input type="checkbox">
                            <div class="slider round"></div>
                        </label>
                    </div>
                </div>
                <div class="row" id="space" style="height: 10px;"></div>
                <div class="row" id="messages">
                    <div class="messages">
                        {% for messages in latest_msg_list %}
                            {% if request.user == messages.receiver %}
                                <div class="row" style="border: 1px solid #ffffff; background-color: #B0B4B7;">
                                    <div class="col-md-1">
                                        <input type="checkbox"
                                               style="margin-top: 15px; margin-left: 20px;">
                                    </div>
                                    <div class="col-md-3 user_name" align="center">{{ messages.sender }}</div>
                                    <div class="col-md-5" align="center">
                                        <div class="audio-player">
                                            <audio controls style="margin-top: 5px;">
                                                <source src="{{ messages.message }}" type="audio/mpeg">
                                            </audio>
                                        </div>
                                    </div>
                                    <div class="col-md-3"></div>
                                </div>
                            {% else %}
                                <div class="row" style="border: 1px solid #ffffff;">
                                    <div class="col-md-1">
                                        <input type="checkbox"
                                               style="margin-top: 15px; margin-left: 20px;">
                                    </div>
                                    <div class="col-md-3"></div>
                                    <div class="col-md-5" align="center">
                                        <div class="audio-player">
                                            <audio controls style="margin-top: 5px;">
                                                <source src="{{ messages.message }}" type="audio/mpeg">
                                            </audio>
                                        </div>
                                    </div>
                                    <div class="col-md-3 user_name" align="center">{{ messages.sender }}</div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="room" id="room">
    <a class="btn btn-info" id="search-toggle">SG</a>
    <form>
        <input type="text" class="search-box" id="search" name="message">
        <!--<button id="button">OK</button>-->
    </form>
</div>

{% csrf_token %}
<div id="search-res" class="search-res"></div>

<script>
    var audioElement = document.createElement('audio');
    audioElement.setAttribute('src', "{% static 'sounds/notification.mp3' %}");

    var dictionary = {};
    {% for user in user_list %}
        dictionary["notification_cnt_{{user.username}}"] = 0;
    {% endfor %}

    var socket = new WebSocket("ws://" + window.location.host + "/{{ conversation_id }}/");
    socket.onmessage = function(e) {
        
        var obj = JSON.parse(e.data);
        if (obj.conversation === "{{conversation_id}}") {
            if (obj.username === "{{ request.user }}") {
                msg = "<div class='row' style='border: 1px solid #ffffff;'>" +
                      "<div class='col-md-1'>" +
                      "<input type='checkbox' style='margin-top: 15px; margin-left: 20px;'></div>" +
                      "<div class='col-md-3'></div>" +
                      "<div class='col-md-5' align='center'>" +
                        "<div class='audio-player'>" +
                            "<audio controls style='margin-top: 5px;'><source src=" + obj.message + " type='audio/mpeg'></audio></div></div>" +
                      "<div class='col-md-3 user_name' align='center'>" + obj.username + "</div>" +
                      "</div>";
            } else {
                msg = "<div class='row' style='border: 1px solid #ffffff; background-color: #B0B4B7;'>" +
                      "<div class='col-md-1'>" +
                      "<input type='checkbox' style='margin-top: 15px; margin-left: 20px;'></div>" +
                      "<div class='col-md-3 user_name' align='center'>" + obj.username + "</div>" +
                      "<div class='col-md-5' align='center'>" +
                        "<div class='audio-player'>" +
                        "<audio controls autoplay style='margin-top: 5px;'><source src=" + obj.message + " type='audio/mpeg'></audio></div></div>" +
                      "<div class='col-md-3'></div>" +
                      "</div>";
            };
        $("#messages").append(msg);

        } else {
            if ((obj.username != "{{ request.user }}") && ("{{ request.user }}" === obj.recipient)) {
                dictionary['notification_cnt_'+obj.username]++;
                counter = dictionary['notification_cnt_'+obj.username]
                $("#notification_"+obj.username).empty();
                $("#notification_"+obj.username).append("<div class='notification'>"+counter+"</div>");
                audioElement.play();
            }
        }
    }


    socket.onopen = function() {
         $("#search-res").on("click", "div.song_list", function(e) {
                            socket.send(this.id);
                            });

         $("#search-res").on("click", "img.audio-play-img", function(e) {
                            return false;
                            });
    }

    if (socket.readyState == WebSocket.OPEN) {
        socket.onopen();
    }

    $('#search-toggle').click(function() {
      if($(this).text().trim() == 'SG') {
        $(this).text('SP');
        $('#search-toggle').removeClass('btn-info').addClass('btn-danger');
      } else if($(this).text().trim() == 'SP') {
        $(this).text('All');
        $('#search-toggle').removeClass('btn-danger').addClass('btn-warning');
      } else {
        $(this).text('SG');
        $('#search-toggle').removeClass('btn-warning').addClass('btn-info');
      }
    });

    $( "#search" ).keyup(function() {
      results =
        "<ul id='search-results'></ul>";
        $( "#search-res" ).css('min-height', '0%');
        $( "#search-res" ).css('max-height', '30%');
        $( "#search-res" ).css('width', $( '#container' ).width()+'px');
        $( "#search-res" ).append(results);
    });

    $('html').click(function(e) {
      if(!$(e.target).is('.search-box, .search-res'))
        {
         $( "#search-res" ).css('min-height', '0px');
         $( "#search-res" ).css('max-height', '0px');
        }
    });

    $( "div.messages" ).scrollTop( 300 );
    // $( "#user_list" ).scrollTop( 300 );
    $( "#search-res" ).scrollTop( 300 );

</script>

{% endblock %}